export default [
  'med plystrende buser',
  'som drikker foran juiceautomaten på hoteller',
  'uten retningssans',
  'som gir meg forefallende ræl',
  'som er umusikalske',
  'som ser på meg',
  'som synger i dusjen',
  'med hentesveis',
  'som minner meg om svigermor',
  'som ikke kan stave',
  'med plirende blikk',
  'uten selvinnsikt',
  'som tar meg i ansiktet',
  'uten humor',
  'uten substans',
  'med uklare mål',
  'som går i takt',
  'som synger falskt',
  'uten utstråling',
  'med personlig innstråling',
  'som er hjelpeløse'
]
