on:
  release:
    types: [published]
    branches: [main]
name: Test and Deploy on release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v4
      with:
        node-version: 14
    - run: npm install
    - run: npm test
    - run: now --prod --confirm --token ${ZEIT_TOKEN}
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
